server:
  port: ${server.port}

# WebSocket 端口
ws:
  port: 10086

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 10
    host: ${redis.url:127.0.0.1}
    port: ${redis.port:6379}
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000